### ISSUE TITLE
Feature: choose custom title text

### ISSUE THREAD

**Issue by noraj** [FHPythonUtils/AnsiToImg#7] opened 2023-02-05 22:10 UTC
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

---

- Be able to remove the titlebar watermark (`AnsiToImg (courtesy of Rich)`)
- Choose custom titlebar text

### Describe the solution you'd like

add a `--titlebar <text>` option that override the hardcoded watermark

**Comment by FredHappyface** [comment] 2023-02-17 11:23
Hey thanks for the request. Seems reasonable tbh. The watermark was intended as a way to credit rich as it really does the heavy lifting here. Originally each rendering function was implemented entirely by this lib, however, I chose to stand on the shoulders of giants in more recent versions. With this in mind, providing credit in this way seemed appropriate.

I'll add this to me Todo. Can't provide a good ETA as I work on this in my spare time

**Comment by dtbaker** [comment] 2023-02-26 13:17
For now I'm converting svg to jpeg and manually cropping the frame out `convert test2.svg -crop 976x582+9+43 test2.jpg`

**Comment by FredHappyface** [comment] 2023-03-07 00:22
Fixed in https://github.com/FHPythonUtils/AnsiToImg/releases/tag/2023.1

**Closed by FredHappyface** 2023-03-07 00:22 UTC
Labels: enhancement
